# build environment
FROM node:16-alpine as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY ./ISEKCap/package.json ./
COPY ./ISEKCap/package-lock.json ./
RUN npm ci
RUN npm install react-scripts@3.4.1 -g --silent
COPY ./ISEKCap .
RUN npm run build
# production environment
FROM nginx:stable-alpine
COPY --from=build /app/dist/isekcap/* /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]